// Mocks generated by Mockito 5.4.2 from annotations
// in van_rec/test/home_screen_vm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:importer/data/data.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:van_rec/data/ds/data_source.dart' as _i2;
import 'package:van_rec/data/repo/event_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataSource_0 extends _i1.SmartFake implements _i2.DataSource {
  _FakeDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMyEvent_1 extends _i1.SmartFake implements _i3.MyEvent {
  _FakeMyEvent_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i4.EventRepository {
  @override
  _i2.DataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
        returnValueForMissingStub: _FakeDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i2.DataSource);

  @override
  _i5.Future<List<_i3.MyEvent>> getEvents({
    String? query,
    int? activityId,
    int? centerId,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [],
          {
            #query: query,
            #activityId: activityId,
            #centerId: centerId,
            #date: date,
          },
        ),
        returnValue: _i5.Future<List<_i3.MyEvent>>.value(<_i3.MyEvent>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.MyEvent>>.value(<_i3.MyEvent>[]),
      ) as _i5.Future<List<_i3.MyEvent>>);

  @override
  _i5.Future<List<_i3.Activity>> getActivities() => (super.noSuchMethod(
        Invocation.method(
          #getActivities,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Activity>>.value(<_i3.Activity>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Activity>>.value(<_i3.Activity>[]),
      ) as _i5.Future<List<_i3.Activity>>);

  @override
  _i5.Future<List<_i3.CenterActivity>> getCenterActivities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCenterActivities,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.CenterActivity>>.value(<_i3.CenterActivity>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.CenterActivity>>.value(<_i3.CenterActivity>[]),
      ) as _i5.Future<List<_i3.CenterActivity>>);

  @override
  _i5.Future<_i3.MyEvent> getEvent({
    required int? id,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvent,
          [],
          {
            #id: id,
            #start: start,
            #end: end,
          },
        ),
        returnValue: _i5.Future<_i3.MyEvent>.value(_FakeMyEvent_1(
          this,
          Invocation.method(
            #getEvent,
            [],
            {
              #id: id,
              #start: start,
              #end: end,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.MyEvent>.value(_FakeMyEvent_1(
          this,
          Invocation.method(
            #getEvent,
            [],
            {
              #id: id,
              #start: start,
              #end: end,
            },
          ),
        )),
      ) as _i5.Future<_i3.MyEvent>);
}
